### ISSUE TITLE
Issues about data format

### ISSUE THREAD

**Issue by liululu1** [kaist-avelab/K-Radar_V1#3]
Hi! Thanks again for sharing the great job! 
I want to know is the complex number format stored in the 4DRT(4D Radar tensor) data? And when will the dataset be made public?

**Comment by DongHeePaek** [comment]
Hello, @liululu1 

I appreciate for your interest in our research, K-Radar.
Each cell of 4DRT data has a single absolute power value in double type.
As such, each 4DRT consists of 65M (64x256x107x37) double type values.
For the next issue, please refer to https://github.com/kaist-avelab/K-Radar/issues/5

Thank you.
