### ISSUE TITLE
About specification for dataset and how to get development kits 

### ISSUE THREAD

**Issue by youngsnail** [kaist-avelab/K-Radar_V1#4]
Hi, Thank you for building and sharing this dataset. It is very useful. Great job!
Could you please provide a specification for how to use dataset, like data format, time synchronization and so on? I just downloaded part of zips (It is too big to be downloaded completely) but didn't found. Maybe it is in one of them?
And, the project mentioned that all development kits and labeling tools will be released too. Could you also show me how to get them please?
Thanks again!

**Comment by DongHeePaek** [comment]
Hello, @youngsnail 

I appreciate for your interest in our research, K-Radar.
Nowadays, we are working on two things for this project:
1) stabilizing the download link and
2) arranging the devkits code (for loading the data, labeling, and training/inferencing the neural networks). 

We will make both of them public, similar to our other project, K-Lane.

Thank you.
