### ISSUE TITLE
NAS server is down

### ISSUE THREAD

**Issue by yizhou-wang** [kaist-avelab/K-Radar_V1#5]
Thanks for the great contribution! But just found that the link to the NAS server is down (https://kaistavelab.direct.quickconnect.to:54568/). Could you please help? Thanks!

**Comment by DongHeePaek** [comment]
Hello, @yizhou-wang 

We appreciate for your interset in our reasearch, K-Lane.
I've noticed that the download link for the network-attached storage (NAS) is unstable and down right now. 
As such, we are preparing the Google Drive download link similar to our other project, K-Lane.
I apologize for supporting this issue directly, but we will provide a reasonable download link for K-Radar around the end of November.

Thank you.
