### ISSUE TITLE
Can you tell us how 4d radar is calibrated with Lidar and camera?

### ISSUE THREAD

**Issue by Yzichen** [kaist-avelab/K-Radar_V1#6]
Can you tell us how 4d radar is calibrated with Lidar and camera?

**Comment by DongHeePaek** [comment]
Hello @Yzichen

We appreciate for your interest in our research.
We introduce the calibration process at section 3.3 and D.3 of 'https://arxiv.org/abs/2206.08171' in detail.

Thank you.
